import esbuild from 'esbuild'
import process from 'process'
import { builtinModules as builtins } from 'node:module'
import esbuildSvelte from 'esbuild-svelte'
import sveltePreprocess from 'svelte-preprocess'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

async function buildWorker(workerPath) {
    const result = await esbuild.build({
        entryPoints: [workerPath],
        bundle: true,
        minify: true,
        write: false,
        outfile: 'worker.js',
        target: 'es2021',
        format: 'cjs',
    })

    return result.outputFiles[0].text
}
let inlineWorkerPlugin = {
    name: 'inline-worker-plugin',
    setup(build) {
        build.onLoad(
            { filter: /\.(service|worker).(js|jsx|ts|tsx)$/ },
            async ({ path: workerPath }) => {
                let workerCode = await buildWorker(workerPath)
                return {
                    contents: `
                export default function inlineWorker() {
                    let blob = new Blob([${JSON.stringify(
                        workerCode,
                    )}], {type: 'text/javascript'})
                    let url = URL.createObjectURL(blob)
                    let worker = ${
                        workerPath.includes('service')
                            ? "navigator.serviceWorker.register(url, {scope: '/'})"
                            : 'new Worker(url)'
                    };
                    URL.revokeObjectURL(url)
                    return worker
                }`,
                    loader: 'js',
                }
            },
        )
    },
}
const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ['main.ts'],
    bundle: true,
    // styles.css is imported as text so HTML exports can embed the same scene CSS
    loader: { '.css': 'text' },
    plugins: [
        inlineWorkerPlugin,
        esbuildSvelte({
            compilerOptions: { css: 'injected' },
            preprocess: sveltePreprocess(),
        }),
    ],
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtins,
    ],
    format: 'cjs',
    target: 'es2018',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'main.js',
})

if (prod) {
    await context.rebuild()
    process.exit(0)
} else {
    await context.watch()
}
