import type { BiomeType, CropType, FloraSpecies, HomesteadBuilding, PlacedHomesteadItem } from '../types/forest'
import { SPECIES_SVGS, BUILDING_SVGS } from './floraAssets'

export const FLORA_SPECIES: FloraSpecies[] = [
    {
        id: 'classic_pine',
        name: 'Classic Pine',
        description: 'A hardy, evergreen conifer that perseveres through all seasons.',
        category: 'tree',
        sunlightCost: 0,
        coinsCost: 0,
        unlockLevel: 1,
        recommendedDuration: 25,
        iconSvg: SPECIES_SVGS.classic_pine,
        color: '#2E7D32',
        charm: 2,
    },
    {
        id: 'sunflower',
        name: 'Sunflower Grove',
        description: 'Radiant bright sunflowers reaching towards the sun. Ideal for quick focus sprints.',
        category: 'flower',
        sunlightCost: 60,
        coinsCost: 5,
        unlockLevel: 1,
        recommendedDuration: 15,
        iconSvg: SPECIES_SVGS.sunflower,
        color: '#FBC02D',
        charm: 2,
    },
    {
        id: 'ancient_oak',
        name: 'Ancient Oak',
        description: 'A grand deciduous tree with deep roots, providing strength for deep work sessions.',
        category: 'tree',
        sunlightCost: 120,
        coinsCost: 10,
        unlockLevel: 2,
        recommendedDuration: 25,
        iconSvg: SPECIES_SVGS.ancient_oak,
        color: '#388E3C',
        charm: 3,
    },
    {
        id: 'lavender',
        name: 'Lavender Field',
        description: 'Aromatic violet spires that reduce stress and sharpen mental clarity.',
        category: 'flower',
        sunlightCost: 150,
        coinsCost: 12,
        unlockLevel: 3,
        recommendedDuration: 20,
        iconSvg: SPECIES_SVGS.lavender,
        color: '#7E57C2',
        charm: 2,
    },
    {
        id: 'autumn_maple',
        name: 'Autumn Maple',
        description: 'Fiery crimson and amber leaves reflecting seasonal productivity and warmth.',
        category: 'tree',
        sunlightCost: 220,
        coinsCost: 18,
        unlockLevel: 4,
        recommendedDuration: 25,
        iconSvg: SPECIES_SVGS.autumn_maple,
        color: '#E65100',
        charm: 3,
    },
    {
        id: 'sakura',
        name: 'Cherry Blossom',
        description: 'Delicate pink sakura blossoms that bring calm, mindful focus.',
        category: 'tree',
        sunlightCost: 260,
        coinsCost: 22,
        unlockLevel: 5,
        recommendedDuration: 25,
        iconSvg: SPECIES_SVGS.sakura,
        color: '#EC407A',
        charm: 4,
    },
    {
        id: 'willow',
        name: 'Weeping Willow',
        description: 'Serene arching boughs trailing gracefully in the gentle breeze.',
        category: 'tree',
        sunlightCost: 300,
        coinsCost: 25,
        unlockLevel: 6,
        recommendedDuration: 30,
        iconSvg: SPECIES_SVGS.willow,
        color: '#81C784',
        charm: 4,
    },
    {
        id: 'bamboo',
        name: 'Bamboo Grove',
        description: 'Resilient and flexible bamboo culms inspiring swift, unbroken focus.',
        category: 'zen',
        sunlightCost: 350,
        coinsCost: 30,
        unlockLevel: 7,
        recommendedDuration: 25,
        iconSvg: SPECIES_SVGS.bamboo,
        color: '#4CAF50',
        charm: 3,
    },
    {
        id: 'bonsai',
        name: 'Zen Bonsai',
        description: 'A meticulously cultivated ancient pine miniature for contemplative deep work.',
        category: 'zen',
        sunlightCost: 450,
        coinsCost: 40,
        unlockLevel: 9,
        recommendedDuration: 35,
        iconSvg: SPECIES_SVGS.bonsai,
        color: '#2E7D32',
        charm: 5,
    },
    {
        id: 'mushroom_circle',
        name: 'Fairy Ring',
        description: 'A mysterious ring of bioluminescent glowing mushrooms humming with magic.',
        category: 'rare',
        sunlightCost: 600,
        coinsCost: 55,
        unlockLevel: 11,
        recommendedDuration: 45,
        iconSvg: SPECIES_SVGS.mushroom_circle,
        color: '#00E5FF',
        charm: 6,
    },
    {
        id: 'golden_tree',
        name: 'Celestial Gold Tree',
        description: 'A mythical glowing tree of knowledge and mastery for monumental deep work sessions.',
        category: 'rare',
        sunlightCost: 1000,
        coinsCost: 90,
        unlockLevel: 14,
        recommendedDuration: 50,
        iconSvg: SPECIES_SVGS.golden_tree,
        color: '#FFD700',
        charm: 10,
    },
]

export const HOMESTEAD_BUILDINGS: HomesteadBuilding[] = [
    {
        id: 'campfire',
        name: 'Hearth Campfire',
        description: 'Warm glowing stones where thoughts gather. The heart of your village.',
        category: 'landmark',
        sunlightCost: 120,
        coinsCost: 10,
        unlockLevel: 1,
        unique: true,
        maxLevel: 5,
        charm: 3,
        perk: { kind: 'vitality_keep_pct', base: 20, perLevel: 10 },
        iconSvg: BUILDING_SVGS.campfire,
    },
    {
        id: 'cobblestone_path',
        name: 'Cobblestone Path',
        description: 'Smooth river stones paving tidy trails. Villagers love to stroll them.',
        category: 'path',
        sunlightCost: 15,
        coinsCost: 1,
        unlockLevel: 1,
        unique: false,
        maxLevel: 1,
        charm: 1,
        iconSvg: BUILDING_SVGS.cobblestone_path,
    },
    {
        id: 'lantern',
        name: 'Stone Lantern',
        description: 'A steady, gentle glow for evening focus sessions.',
        category: 'decoration',
        sunlightCost: 60,
        coinsCost: 6,
        unlockLevel: 1,
        unique: false,
        maxLevel: 3,
        charm: 2,
        perk: { kind: 'night_sunlight_pct', base: 10, perLevel: 5 },
        iconSvg: BUILDING_SVGS.lantern,
    },
    {
        id: 'bench',
        name: 'Garden Bench',
        description: 'A carved bench for reviewing your notes and ticking off tasks.',
        category: 'decoration',
        sunlightCost: 80,
        coinsCost: 8,
        unlockLevel: 1,
        unique: false,
        maxLevel: 3,
        charm: 2,
        perk: { kind: 'task_coins', base: 1, perLevel: 1 },
        iconSvg: BUILDING_SVGS.bench,
    },
    {
        id: 'water_stream',
        name: 'Babbling Brook',
        description: 'A clear sparkling stream tile. Connect several into a river.',
        category: 'path',
        sunlightCost: 25,
        coinsCost: 2,
        unlockLevel: 2,
        unique: false,
        maxLevel: 1,
        charm: 1,
        iconSvg: BUILDING_SVGS.water_stream,
    },
    {
        id: 'garden_plot',
        name: 'Garden Plot',
        description: 'Tilled soil for a crop. It grows with every minute you focus and waits for you to harvest it.',
        category: 'farm',
        sunlightCost: 60,
        coinsCost: 6,
        unlockLevel: 2,
        unique: false,
        limit: 6,
        maxLevel: 1,
        charm: 2,
        iconSvg: BUILDING_SVGS.garden_plot,
    },
    {
        id: 'hay_bale',
        name: 'Hay Bale',
        description: 'A rolled bale of golden hay. Smells like late summer.',
        category: 'decoration',
        sunlightCost: 30,
        coinsCost: 3,
        unlockLevel: 2,
        unique: false,
        maxLevel: 1,
        charm: 1,
        iconSvg: BUILDING_SVGS.hay_bale,
    },
    {
        id: 'stone_well',
        name: 'Village Well',
        description: 'An old cobblestone well. Fresh water keeps the village prosperous.',
        category: 'building',
        sunlightCost: 200,
        coinsCost: 20,
        unlockLevel: 2,
        unique: true,
        maxLevel: 5,
        charm: 3,
        perk: { kind: 'coins_pct', base: 10, perLevel: 5 },
        iconSvg: BUILDING_SVGS.stone_well,
    },
    {
        id: 'bridge',
        name: 'Wooden Footbridge',
        description: 'A graceful arched bridge. Place it over a brook.',
        category: 'decoration',
        sunlightCost: 120,
        coinsCost: 12,
        unlockLevel: 3,
        unique: false,
        maxLevel: 1,
        charm: 4,
        iconSvg: BUILDING_SVGS.bridge,
    },
    {
        id: 'scarecrow',
        name: 'Friendly Scarecrow',
        description: 'Keeps the crows away and the crops company, so they grow faster.',
        category: 'decoration',
        sunlightCost: 90,
        coinsCost: 9,
        unlockLevel: 3,
        unique: false,
        maxLevel: 3,
        charm: 2,
        perk: { kind: 'crop_growth_pct', base: 15, perLevel: 10 },
        iconSvg: BUILDING_SVGS.scarecrow,
    },
    {
        id: 'chicken_coop',
        name: 'Chicken Coop',
        description: 'Hens that roam the village and lay fresh eggs for your first tree of the day.',
        category: 'building',
        sunlightCost: 260,
        coinsCost: 26,
        unlockLevel: 4,
        unique: true,
        maxLevel: 3,
        charm: 5,
        perk: { kind: 'first_tree_coins', base: 3, perLevel: 2 },
        iconSvg: BUILDING_SVGS.chicken_coop,
    },
    {
        id: 'gazebo',
        name: 'Tea Gazebo',
        description: 'A tranquil pavilion that rewards you for actually taking your breaks.',
        category: 'landmark',
        sunlightCost: 320,
        coinsCost: 30,
        unlockLevel: 4,
        unique: true,
        maxLevel: 5,
        charm: 5,
        perk: { kind: 'break_sunlight', base: 5, perLevel: 3 },
        iconSvg: BUILDING_SVGS.gazebo,
    },
    {
        id: 'cabin',
        name: 'Cozy Cabin',
        description: 'A log cabin with a smoking chimney to shelter your focus.',
        category: 'building',
        sunlightCost: 450,
        coinsCost: 45,
        unlockLevel: 5,
        unique: true,
        maxLevel: 5,
        charm: 6,
        perk: { kind: 'sunlight_pct', base: 10, perLevel: 5 },
        iconSvg: BUILDING_SVGS.cabin,
    },
    {
        id: 'torii_gate',
        name: 'Torii Gate',
        description: 'A vermilion gateway marking the threshold into deep focus.',
        category: 'landmark',
        sunlightCost: 400,
        coinsCost: 40,
        unlockLevel: 6,
        unique: true,
        maxLevel: 5,
        charm: 6,
        perk: { kind: 'quest_bonus_pct', base: 20, perLevel: 10 },
        iconSvg: BUILDING_SVGS.torii_gate,
    },
    {
        id: 'watermill',
        name: 'River Watermill',
        description: 'A turning wheel that keeps the village running, even on days you rest.',
        category: 'building',
        sunlightCost: 700,
        coinsCost: 65,
        unlockLevel: 8,
        unique: true,
        maxLevel: 3,
        charm: 7,
        perk: { kind: 'streak_shield', base: 1, perLevel: 1 },
        iconSvg: BUILDING_SVGS.watermill,
    },
    {
        id: 'greenhouse',
        name: 'Glass Conservatory',
        description: 'A botanical glass palace where knowledge grows faster.',
        category: 'landmark',
        sunlightCost: 850,
        coinsCost: 80,
        unlockLevel: 10,
        unique: true,
        maxLevel: 5,
        charm: 8,
        perk: { kind: 'xp_pct', base: 15, perLevel: 10 },
        iconSvg: BUILDING_SVGS.greenhouse,
    },
    {
        id: 'windmill',
        name: 'Dutch Windmill',
        description: 'Grand sails that catch the wind of long, deep sessions.',
        category: 'building',
        sunlightCost: 800,
        coinsCost: 80,
        unlockLevel: 12,
        unique: true,
        maxLevel: 5,
        charm: 8,
        perk: { kind: 'long_session_sunlight_pct', base: 20, perLevel: 10 },
        iconSvg: BUILDING_SVGS.windmill,
    },
]

export function getSpecies(id: string): FloraSpecies | undefined {
    return FLORA_SPECIES.find((s) => s.id === id)
}

export function getBuilding(id: string): HomesteadBuilding | undefined {
    return HOMESTEAD_BUILDINGS.find((b) => b.id === id)
}

/** Crops for garden plots. Slower crops pay a little more per minute. */
export const CROPS: CropType[] = [
    {
        id: 'carrot',
        name: 'Carrots',
        icon: '🥕',
        description: 'Quick and cheerful: ready after about two focus sessions.',
        growMinutes: 50,
        coins: 2,
        xp: 3,
        unlockLevel: 1,
    },
    {
        id: 'tomato',
        name: 'Tomatoes',
        icon: '🍅',
        description: 'The pomodoro itself. Ripens over a good day of focus.',
        growMinutes: 100,
        coins: 5,
        xp: 6,
        unlockLevel: 3,
    },
    {
        id: 'wheat',
        name: 'Golden Wheat',
        icon: '🌾',
        description: 'A swaying golden patch for steady, patient work.',
        growMinutes: 150,
        coins: 8,
        xp: 10,
        unlockLevel: 5,
    },
    {
        id: 'pumpkin',
        name: 'Pumpkins',
        icon: '🎃',
        description: 'Slow and heavy. The biggest harvest for the longest focus.',
        growMinutes: 250,
        coins: 15,
        xp: 18,
        unlockLevel: 8,
    },
]

export const GARDEN_PLOT_ID = 'garden_plot'

/** Unknown or missing ids fall back to carrots, so a plot is never empty. */
export function getCrop(id?: string): CropType {
    return CROPS.find((c) => c.id === id) || CROPS[0]
}

/** How far a plot's crop has grown, 0..1 (1 = ready to harvest). */
export function cropProgress(item: Pick<PlacedHomesteadItem, 'cropId' | 'cropGrowth'>): number {
    return Math.max(0, Math.min(1, (item.cropGrowth || 0) / getCrop(item.cropId).growMinutes))
}

export function isRipePlot(item: PlacedHomesteadItem): boolean {
    return item.itemType === 'building' && item.itemId === GARDEN_PLOT_ID && cropProgress(item) >= 1
}

export const BIOME_UNLOCK_LEVELS: Record<BiomeType, number> = {
    meadow: 1,
    sakura_garden: 3,
    autumn_valley: 5,
    alpine_frost: 8,
    twilight_moss: 12,
}

/** Buying land grows the square village plot one row/column at a time. */
export const LAND_EXPANSIONS: { size: number; unlockLevel: number; sunlightCost: number; coinsCost: number }[] = [
    { size: 6, unlockLevel: 3, sunlightCost: 300, coinsCost: 30 },
    { size: 7, unlockLevel: 7, sunlightCost: 700, coinsCost: 70 },
    { size: 8, unlockLevel: 12, sunlightCost: 1400, coinsCost: 140 },
]

/** Placed trees can be nurtured up to this level (they render larger). */
export const TREE_MAX_LEVEL = 3

export const BASE_LAND_SIZE = 5
export const MAX_LAND_SIZE = 8
